### DISCUSSION TITLE
Every entry of the first column of any table is offset. CSS issue?

### DISCUSSION THREAD

**Discussion by eyyyyyyy3** [fuma-nama/fumadocs#1071] [Q&A] [answered]
![grafik](https://github.com/user-attachments/assets/ef1ef14a-cdb3-472d-8c37-fdccc4c93ab7)
I use tailwind, in `layout.tsx` I import `global.css` and in `global.css` I import fumadocs css `@import "fumadocs-ui/style.css";` Everything is applied as it should be but the table are not as expected. `tailwind.config.js` is unchanged

**Comment by fuma-nama** [comment, marked as answer]
Probably got overriden when building with default Tailwind CSS config.

You can use this as a temporary fix:
```css
th {
  padding: 10px !important;
}

td {
  padding: 10px !important;
}
```
