### DISCUSSION TITLE
What is the best way to override MDX styles?

### DISCUSSION THREAD

**Discussion by EnhancedJax** [fuma-nama/fumadocs#1225] [Q&A] [answered]
I've been styling the spacing in the MDX by adding this to the global CSS file:
```css
article {
  li {
    margin: 0 !important;
  }

  table {
    background-color: hsl(var(--card) / 0.4) !important;
    width: unset !important;
    margin-left: auto !important;
    margin-right: auto !important;
  }

  th {
    background-color: hsl(var(--muted) / 0.4) !important;
  }
}
```

But of course, setting important is not the best way. What would be the conventional / intended way to override MDX styles? Thanks
