### DISCUSSION TITLE
How to enable line numbers on code block?

### DISCUSSION THREAD

**Discussion by ritiksharmarj** [fuma-nama/fumadocs#1464] [Q&A] [answered]
I want to add a line number to each line of code, such as 1, 2, 3, etc. How to??

<img width="491" alt="Screenshot 2025-02-22 at 16 40 37" src="https://github.com/user-attachments/assets/04b492f7-de31-4ef4-a502-35e1f4e83ab0" />

**Comment by fuma-nama** [comment, marked as answer]
You can customise it with CSS, we don't offer that by default

**Comment by ritiksharmarj** [comment]
```css
code {
  counter-reset: step;
  counter-increment: step 0;
}

code .line::before {
  content: counter(step);
  counter-increment: step;
  @apply text-fd-muted-foreground/60 mr-4 inline-block w-4 text-right;
}
```
