### DISCUSSION TITLE
How To Customise Light and Dark Background Colours?

### DISCUSSION THREAD

**Discussion by dcs3spp** [fuma-nama/fumadocs#1556] [Q&A] [answered]
I am trying to customise the background colour for light and dark mode. In the docs I have seen this [section on colours](https://fumadocs.vercel.app/docs/ui/theme#colors) and this [section on light/dark mode](https://fumadocs.vercel.app/docs/ui/layouts/root-provider#theme-provider).

So far I have tried configuring the `tailwind.config.js` with *preset* configured with `addGlobalColors: true`, like shown below:

**tailwind.config.js**

```js
// @ts-check
import { createPreset, presets } from "fumadocs-ui/tailwind-plugin";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./content/**/*.{md,mdx}",
    "./mdx-components.{ts,tsx}",
    "./node_modules/fumadocs-ui/dist/**/*.js",
    "./node_modules/fumadocs-openapi/dist/**/*.js",
  ],
  // presets: [createPreset()],
  presets: [
    createPreset({
      addGlobalColors: true,
      // preset: {
      //  ...presets.default,
      //  light: {
      //    ...presets.default.light,
      //  },
      //  dark: {
      //    ...presets.default.dark,
      //  },
    }),
  ],
};
``` 

Then I try setting the fumadocs colour variables in `global.css` as shown below, based on this [documentation](https://fumadocs.vercel.app/docs/ui/theme#colors).

**global.css**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-fd-background: hsl(120, 100%, 50%);
}

.dark {
  --color-fd-background: hsl(0, 0%, 0%);
}
```

How to change the background colour for light and dark mode?

**Comment by fuma-nama** [comment, marked as answer]
Fumadocs v15 had migrated to Tailwind CSS v4, and the docs is written for v15 which suggests new syntax and language features of Tailwind, perhaps you will want to see the previous docs: https://fumadocs-57gup8ra8-sonmoosans-projects.vercel.app/docs/ui

**Reply by dcs3spp** [reply]
Great many thanks @fuma-nama that solved the issue, I am currently on v14 so will upgrade to v15. For now I have set global.css for compatibility with v14:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --fd-background: 120 100% 50%;
}

.dark {
  --fd-background: 0 0% 0%;
}
```
