### DISCUSSION TITLE
Is there a way to get the codegen to respect the openapi securitySchemas or am I missing something?

### DISCUSSION THREAD

**Discussion by msywulak** [fuma-nama/fumadocs#923] [Q&A] [answered]
```
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
```
I have this set in the openapi docs and can't seem to get the code preview to show it properly but it does show in the page. Do I need to customize it on the per page basis some how?

![Screenshot 2024-10-03 094454](https://github.com/user-attachments/assets/eaf3163f-a86e-4f53-94c2-70ab58eb8ee4)
