### DISCUSSION TITLE
Where to add the rehype plugin ?

### DISCUSSION THREAD

**Discussion by Gitstar-OC** [fuma-nama/fumadocs#946] [Q&A] [answered]
As told in this, do I have to add this https://fumadocs.vercel.app/docs/headless/mdx/rehype-code#usage. 

```ts
import { defineDocs, defineConfig } from 'fumadocs-mdx/config';
import rehypeKatex from 'rehype-katex';
import remarkMath from 'remark-math';
import { rehypeCode } from 'fumadocs-core/mdx-plugins';


export const { docs, meta } = defineDocs(
  {
  docs: {
    dir: 'content/learn'
  },
  meta: {
    dir: 'content/learn'
  }
}
);

export default defineConfig({
  mdxOptions: {
      remarkPlugins: [remarkMath],
      rehypePlugins: (v) => [rehypeKatex, rehypeCode, ...v],
  },
});
```

But it is not working, I have installed shiki and referred to the docs and they look way more complicated than this. Any solution ?

**Comment by fuma-nama** [comment]
Rehype code is added by default, you don't need any configuration to enable syntax highlighting

**Comment by Gitstar-OC** [comment]
I think it is having some error then, this is how I want the code block to look like  (neglect the errors) 

![Screenshot 2024-10-11 204259](https://github.com/user-attachments/assets/01e03536-b072-4174-86cd-91419ce5c85f)
 
and this is it's current look 
![Screenshot 2024-10-11 204322](https://github.com/user-attachments/assets/ed4ccbf8-8c23-4f88-a1d7-62e74fa8814e)

**Reply by fuma-nama** [reply]
Looks like a font problem

**Reply by Gitstar-OC** [reply]
means, do I have to use a specific font ? I just changed the font size of the code block component like this 

```css
.prose :where(p):not(:where([class~="not-prose"], [class~="not-prose"] *)),
.prose :where(code):not(:where([class~="not-prose"], [class~="not-prose"] *)), 
.prose :where(ul):not(:where([class~="not-prose"], [class~="not-prose"] *)), 
.fd-codeblock code {
  font-size: var(--p-size);
}
```
along with this 
```css
.fd-codeblock code {
  row-gap: 5px;
}
```
to add some gap in between the lines. 

And after removing the styling they still look like this 

![Screenshot 2024-10-11 220842](https://github.com/user-attachments/assets/764cc39d-8e1d-4183-8f57-4d4091445bc3)
