### ISSUE TITLE
Handle variable OpenAPI server urls

### ISSUE THREAD

**Issue by johanohly** [fuma-nama/fumadocs#1131]
### What problem will this feature address?

I am currently rewriting the docs of my self-hostable app, which means that the API url that is used differs from user to user. It would be pretty cool if the server url could be customizable by the end user, and it is actually part of the openapi spec: https://swagger.io/docs/specification/v3_0/api-host-and-base-path/#

### Describe the solution you'd like

Show an input when the server url is set to variable, so the user needs to set their own URL to be able to test the endpoints. 

### Describe alternatives you've considered

Not having a server URL but that would be a shame, as the interactive playground would be awesome. 

### Additional context

Definition: 
```
servers:
  - url: '{protocol}://{fqdn}/api'
    description: 'The API is running at `/api` of your AirTrail instance.'
    variables:
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'https'
      fqdn:
        default: 'airtrail.example.com'
```
Swagger Editor example:
![image](https://github.com/user-attachments/assets/b9e8a662-876d-48e3-b7ca-304937932414)

(I don't necessarily need the variables, one input with the whole base url would be awesome as well)

**Comment by fuma-nama** [comment]
Supported, welcome to test it out!

**Comment by johanohly** [comment]
After updating to the latest version of all packages, I get this error after adding the following to the openapi config:
```
 ⨯ TypeError: Invalid URL
    at stringify (<anonymous>)
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
digest: "1139823020"
 GET /docs/api/flight/list-flights 500 in 13607ms
```
```
servers:
  - url: '{protocol}://{origin}/api'
    description: 'The API is running at `/api` of your AirTrail instance.'
    variables:
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'https'
      origin:
        default: 'airtrail.example.com'
```
