### ISSUE TITLE
Cannot override navbar with custom component for notebook mode

### ISSUE THREAD

**Issue by dtbuchholz** [fuma-nama/fumadocs#1357]
### To Reproduce

1. Create a boilerplate app with the CLI, install deps, and follow the steps [here](https://fumadocs.vercel.app/docs/ui/layouts/docs#replacing-navbar)
2. Set up your app to use `notebook` mode
```tsx
import { DocsLayout, type DocsLayoutProps } from "fumadocs-ui/layouts/notebook";
```
3. Update the `layout.tsx`, and the navbar is unaffected. Instead, this removes the nav sidebar logo but doesn't render the custom content
```tsx
export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className="flex flex-col min-h-screen">
        <RootProvider>
          <DocsLayout
            {...baseOptions}
            tree={source.pageTree}
            nav={{
              component: <div>test navbar 1</div>,
            }}
          >
            {children}
          </DocsLayout>
        </RootProvider>
      </body>
    </html>
  );
}
```
3. Also, try to do this in your `layout.config.tsx`, and update your base layout with a custom nav:
```tsx
export const baseOptions: BaseLayoutProps = {
  nav: {
    component: <div>test navbar 2</div>,
  },
};
```
4. Nothing seems to change; the navbar is the same
5. Switch to `import { DocsLayout, type DocsLayoutProps } from "fumadocs-ui/layouts/docs";`, and both of our custom navbars will work (based on precedence).

Note this is using a setup where we use a catchall `[[...slug]]` instead of putting content under a docs route (as described in this discussion [here](https://github.com/fuma-nama/fumadocs/discussions/1350)).

### Current vs. Expected behavior

I should be able to customize the navbar, but I cannot.

Note that my main use case is that I want to:
- Alter the alignment of navbar items
- Add classes to the navbar items (so that I can, e.g., explicitly put certain items on the left or right side of the nav)
- Add an "external" icon for navbar links that arent directly on the site (and also push them to the right hand side)

### Provide environment information

```bash
MacOs
Node v23
pnpm v9.15

All latset fumadocs deps
"fumadocs-core": "15.0.0",
"fumadocs-docgen": "^1.3.5",
"fumadocs-mdx": "11.3.2",
"fumadocs-twoslash": "^3.0.0",
"fumadocs-ui": "15.0.0",
```

### Which area(s) are affected? (Select all that apply)

UI

**Comment by dtbuchholz** [comment]
quick note: i ended up customizing the nav in a bit of a hacky way with CSS. it's not the most ideal approach, but it gives me what I need:

<img width="1241" alt="Image" src="https://github.com/user-attachments/assets/d1279b93-390a-4671-99fe-909fc5b6091b" />

```css
#nd-subnav .flex-1 {
  display: flex !important;
  justify-content: space-between !important; 
}

#nd-subnav .flex-1 > :not(a[rel="noreferrer noopener"][target="_blank"]) {
  margin-right: auto !important;
}

#nd-subnav
  a[rel="noreferrer noopener"][target="_blank"]:not(:has(svg)):last-child {
  margin-right: 1rem !important;
}

```
