### ISSUE TITLE
Add OAuth support

### ISSUE THREAD

**Issue by mrzmyr** [fuma-nama/fumadocs#1405]
### What problem will this feature address?

The Authentication section is empty when using `oauth2` in yaml.

Is OAuth supported yet? If not, where would I start to dig to add support for it? 🫶

```yaml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://*.com//oauth/token?audience=https://*.com/api
          scopes:
            read:customers: Read customer information
            write:customers: Modify customer information
        authorizationCode:
          tokenUrl: https://*.com//oauth/token?audience=https://*.com/api
          authorizationUrl: https://*.com//authorize
          scopes:
            read:customers: Read customer information
            write:customers: Modify customer information
      description: OAuth2 authentication
```

![Image](https://github.com/user-attachments/assets/90dcdd9b-94c1-48b6-8a14-d2177d1d7612)

### Describe the solution you'd like

![Image](https://github.com/user-attachments/assets/bc0146b7-ca8c-4cc8-9296-47cb4b7b45c0)

### Describe alternatives you've considered

-

**Comment by fuma-nama** [comment]
Hmm cannot seems to reproduce it, how did you specify the `security` field? Like:

```yaml
security:
  - oauth: []
```

or at other level?

![Image](https://github.com/user-attachments/assets/1aa913c3-96a6-4bfc-bbc9-475a6aa9879c)

**Comment by fuma-nama** [comment]
and yes we don't support flow authentication flow right now, personally I would want to support that in a way that people could easily customise, like replacing the auth section with their component

**Comment by mrzmyr** [comment]
> Hmm cannot seems to reproduce it, how did you specify the `security` field? Like:
> 
> security:
>   - oauth: []
> or at other level?
> 
> ![Image](https://github.com/user-attachments/assets/1aa913c3-96a6-4bfc-bbc9-475a6aa9879c)

did you try this setup?

```yaml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://*.com//oauth/token?audience=https://*.com/api
          scopes:
            read:customers: Read customer information
            write:customers: Modify customer information
        authorizationCode:
          tokenUrl: https://*.com//oauth/token?audience=https://*.com/api
          authorizationUrl: https://*.com//authorize
          scopes:
            read:customers: Read customer information
            write:customers: Modify customer information
      description: OAuth2 authentication
```

**Comment by mrzmyr** [comment]
> and yes we don't support flow authentication flow right now, personally I would want to support that in a way that people could easily customise, like replacing the auth section with their component

If I would start digging in the code to implement it, where would I start? :)

**Comment by fuma-nama** [comment]
I can implement it later next month

If you want to help, you can start from https://github.com/fuma-nama/fumadocs/blob/6b5de71c8bade73962f78b3ad34e82a0d9062f89/packages/openapi/src/render/operation.tsx#L267

**Comment by mrzmyr** [comment]
sounds good, let me know if I should give it a quick spin on our open api spec :)

Did this setup worked for you?

```yaml
security:
  - oauth2:
      - users:read:none
```

**Comment by mrzmyr** [comment]
btw, working now: 

![Image](https://github.com/user-attachments/assets/9de8929d-b4f6-43be-b070-189c35d5cb61)

Was missing the scheme:

```yaml
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: [URL]
          scopes: 
            - users:read:none: 'users:read:none '

```
