### ISSUE TITLE
OpenAPI: Add `required` label to required requestBody params

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#729]
### What problem will this feature address?

This new label addition will improve the generated documentation for the OpenAPI interactive playground and will help developers understand better the exact requirements of a request.

### Describe the solution you'd like

Each required params of the requestBody should have a `required` label next to their titles.

### Describe alternatives you've considered

There don't seem to be any solutions to this at the moment.

### Additional context

Take for example the "Buy Museum Tickets" POST request. According to the OpenAPI yaml schema file, it has the following required params in the requestBody:
```yaml
BuyMuseumTicketsRequest:
    # ...
    required:
        - ticketType
        - ticketDate
        - email
```
However, there is no indication in the generated page which of the request body params are required or not (see screenshot attached).

<img width="568" alt="Screenshot 2024-08-19 at 10 45 34" src="https://github.com/user-attachments/assets/57e61d98-ab86-4c89-af7c-41025a766b44">
