### ISSUE TITLE
OpenAPI: Duplicate `Content-Type` header in cURL request sample

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#739]
### To Reproduce

1. Include a Content-Type parameter in the `/special-events` schema definition of the museum-api.yaml file.
```yaml
/special-events:
    post:
      summary: Create special events
      description: Creates a new special event for the museum.
      operationId: createSpecialEvent
      parameters:
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            enum:
              - application/json
 ```
2. Generate the docs.
3. Visit the related page.
4. Check the generated sample code for the `cURL` command.

### Current vs. Expected behavior

**Current behavior:**
There's a duplicate `-H "Content-Type: application/json" \` in the generated `cURL` sample request.
<img width="422" alt="Screenshot 2024-08-22 at 17 09 52" src="https://github.com/user-attachments/assets/104500ef-dc3e-4799-a03b-7d44daeaa7e1">

**Expected behavior:**
There should be only one header for the Content-Type `-H "Content-Type: application/json" \` in the generated `cURL` sample request.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.21
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.6 // Latest available version is detected (14.2.6).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g OpenAPI, Typescript DocsGen)
