### ISSUE TITLE
OpenAPI: Server selector to allow interacting with different API environments

### ISSUE THREAD

**Issue by CosAnca** [fuma-nama/fumadocs#783]
### What problem will this feature address?

An OpenAPI schema can define a list of servers, and this is a quite common use case for many APIs.
```yaml
servers:
  - url: "https://dev.api.myapp.com/v1"
     description: Development
  - url: "https://stating.api.myapp.com/v1"
     description: Staging
  - url: "https://prod.api.myapp.com/v1"
```
However, the generated OpenAPI doc pages in the interactive playground seems to only use the first item defined in the servers list and currently there doesn't seem to be a way to change this to allow users to interact with other environments.

### Describe the solution you'd like

Add a "Server" dropdown selector above the request path (with its default value set to the first item in the servers list)
When clicked, the dropdown will reveal a list of all the servers defined in the OpenAPI schema.
Selecting a specific server, should then apply that base url when the request is sent.

Also, for an improved experience, the selected server should be synchronised and persisted across different OpenAPI docs generated pages.

<img width="992" alt="Screenshot 2024-08-31 at 16 59 34" src="https://github.com/user-attachments/assets/2e81dc91-3c31-4b15-87b6-2d884c468c7c">

Expanded:
<img width="995" alt="Screenshot 2024-08-31 at 16 59 20" src="https://github.com/user-attachments/assets/c6b304e6-7004-4977-afc6-ac120e0c7f51">

### Describe alternatives you've considered

There doesn't seem to be an alternative at the moment to allow users to interact with different API environments from the API Playground in the generated OpenAPI docs.
